# ===========================================
# APPLICATION
# ===========================================
spring.application.name=form-builder
server.port=8080

# ===========================================
# POSTGRESQL DATABASE
# ===========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/form_builder
spring.datasource.username=postgres
spring.datasource.password=hasian
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================================
# JPA / HIBERNATE
# ===========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================================
# JWT
# ===========================================
app.jwt.secret=H4r3Bu51n3ssC0nsult1ngS3cr3tK3yF0rJWT2024!
app.jwt.expiration=86400000

# ===========================================
# SWAGGER
# ===========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html